Fix CBFS comparator with our_check_output()
The cbfs tests were broken by fe446ea2eda5f9649b829985f9fd01b151b81fe5
They would fail with:
TypeError: a bytes-like object is required, not 'str'

Additionally, our_check_output() can't accept a stdout= argument since
subprocess.check_output doesn't accept this argument.